author: 
  name: "Andrés Jorge Giménez Muñoz"
  email: "agimenezmunoz@educa.madrid.com" 
  watermark: "Profesor: andrés"
school:
  name: "IES Gabriela Mistral"
  logo: logo-ies_gabriela_mistral.png
exam-info:
   academic-period: "Curso 2025/2026"
show-solutions: true
