version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - binomial
  - Bolzano
  - derivabilidad
  - derivable
  - Fern√°n
  - IES
  - inecuaciones
  - Inecuaciones
  - StudentData
ignoreWords: []
import: []
language: es-ES,en-UK
