version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - academic
  - approx
  - arccos
  - arctan
  - author
  - Barrow
  - bicuadradas
  - binomial
  - black
  - blue
  - Bolzano
  - bottom
  - canvas
  - cetz
  - circle
  - clarification
  - clarifications
  - columns
  - community
  - derivabilidad
  - derivable
  - dispatch
  - draw
  - Dyslexic
  - exam
  - examples
  - Fern√°n
  - fill
  - find
  - font
  - github
  - gutter
  - IES
  - iname
  - inecuaciones
  - Inecuaciones
  - length
  - line
  - math
  - north
  - padding
  - pages
  - plot
  - print
  - question
  - questions
  - right
  - Ruffini
  - school
  - separator
  - setup
  - stroke
  - student
  - StudentData
  - style
  - subject
  - subquestion
  - theta
  - typst
  - watermark
  - while
  - white
ignoreWords: []
import: []
language: es-ES,en-UK
