version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - academic
  - approx
  - arctan
  - author
  - binomial
  - black
  - blue
  - Bolzano
  - bottom
  - canvas
  - cetz
  - circle
  - columns
  - derivabilidad
  - derivable
  - draw
  - Dyslexic
  - exam
  - Fern√°n
  - fill
  - font
  - IES
  - inecuaciones
  - Inecuaciones
  - length
  - line
  - math
  - north
  - padding
  - pages
  - plot
  - question
  - questions
  - school
  - separator
  - stroke
  - student
  - StudentData
  - style
  - subject
  - subquestion
  - theta
  - watermark
  - white
ignoreWords: []
import: []
language: es-ES,en-UK
